---
# tasks file for vector-role
- name: Install Vector
  become: true
  block:
# Install in CentOS
  - name: Vector | Get vector distrib | CentOS
    ansible.builtin.get_url:
      url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm
      dest: ./vector-{{ vector_version }}-1.x86_64.rpm
      mode: 0755
    when: ansible_facts.distribution == "CentOS"
  - name: Vector | Install vector rpm | CentOS
    ansible.builtin.yum:
      name: vector-{{ vector_version }}-1.x86_64.rpm
      disable_gpg_check: true
    when: ansible_facts.distribution == "CentOS"
    notify: Start vector service | CentOS
  - name: Add vector user to systemd-journal group | CentOS
    user:
      name: vector
      groups: systemd-journal
      append: true
    when: ansible_facts.distribution == "CentOS"

# Install in Ubuntu
  - name: Get Vector distrib | Ubuntu
    ansible.builtin.get_url:
      url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
      dest: "./vector_{{ vector_version }}-1_amd64.deb"
      mode: 0755
    when: ansible_facts.distribution == "Ubuntu"
  - name: Create systemd unit Vector
    become: true
    template:
      src: vector.service.j2
      dest: /etc/systemd/system/vector.service
      mode: 0644
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_gid }}"
    when: ansible_facts.distribution == "Ubuntu"

  - name: Install Vector packages | Ubuntu
    become: true
    ansible.builtin.apt:
      deb: vector_{{ vector_version }}-1_amd64.deb
    notify: Start Vector service | Ubuntu
    when: ansible_facts.distribution == "Ubuntu"

  - name: Add vector user to systemd-journal group | Ubuntu
    user:
      name: vector
      groups: messagebus
      append: true
    when: ansible_facts.distribution == "Ubuntu"

  - name: Vector | Update vector config
    ansible.builtin.lineinfile:
      path: /etc/default/vector
      regexp: 'VECTOR_CONFIG='
      line: VECTOR_CONFIG=/etc/vector/config.yaml
  - name: Vector | Create vector config
    ansible.builtin.copy:
      dest: /etc/vector/config.yaml
      mode: 0644
      content: |
        {{ vector_config | to_nice_yaml(indent=2) }}

